### ISSUE TITLE
Rename and add Colab link

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/Dual-Deployments-on-Vertex-AI#1]
@deep-diver could you change the name of the `dual_deployments_with_AutoML.ipynb` notebook (adjust casing basically) to match the naming of the rest of the notebooks? Also, please add a Colab Notebook link. You can directly commit your notebook from Colab and it'd provide you an option of whether to include a Colab link or not. 

Something like the following:

![image](https://user-images.githubusercontent.com/22957388/127586726-e08512e1-fc91-4f2c-95c4-f6c0f1f881a8.png)

Also, please add a small description at the beginning of the notebook to let the readers know what the notebook is about. You can refer to [this notebook](https://github.com/sayakpaul/Dual-Deployments-on-Vertex-AI/blob/main/notebooks/Dataset_Prep.ipynb) for an example.

**Comment by deep-diver** [comment]
@sayakpaul 

I just did what you have asked!
Please check it out :) 

and thanks for letting me know

**Comment by sayakpaul** [comment]
Beautiful. Thank you.
