### ISSUE TITLE
Specifications for `firebase_publisher.py`

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/Dual-Deployments-on-Vertex-AI#7]
Referring to [`firebase_publisher.py`](https://github.com/sayakpaul/Dual-Deployments-on-Vertex-AI/blob/main/custom_components/firebase_publisher.py). Could you provide a note on `credential.json`? Feel free to directly commit that to the script itself.

**Comment by deep-diver** [comment]
added some explanation about the signature

https://github.com/sayakpaul/Dual-Deployments-on-Vertex-AI/blob/main/custom_components/firebase_publisher.py
